version: '3'

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./util/configs/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080