version: '3'

services:

  ui:
    build:
      context: .
      dockerfile: ./ui/Docker/Dockerfile
    ports:
      - 7001:80
    depends_on:
      - api
    restart: always

  api:
    build:
      context: .
      dockerfile: ./api/docker/Dockerfile
    ports:
      - 7000:8080
    env_file:
      - api/.env
    entrypoint: ["/bin/sh","-c"]
    command: 
      - | 
          while ! nc -z db 5432; 
          do sleep 1; 
          done;
          ./migration up;
          chmod +x ./main;
          ./main;
    depends_on:
      - db
    restart: always

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: diarynote_db
      POSTGRES_USER: diarynote_user
      POSTGRES_PASSWORD: diarynote_pass
    ports:
      - "5432:5432"
    restart: always