version: '3'

services:
  ui:
    build:
      context: .
      dockerfile: ./ui/Docker/Dockerfile
    ports:
      - 7001:80
    environment:
      - BASE_URL=http://${{ secrets.LINODE_IP }}:7000  # Pass BASE_URL here
    depends_on:
      - api
    restart: always

  api:
    build:
      context: .
      dockerfile: ./api/docker/Dockerfile
    ports:
      - 7000:8080
    env_file:
      - api/.env
    environment:
      - BASE_URL=http://${{ secrets.LINODE_IP }}:7000  # Pass BASE_URL here
    entrypoint: ["/bin/sh","-c"]
    command: 
      - | 
          while ! nc -z db 5432; 
          do sleep 1; 
          done;
          ./migration up;
          chmod +x ./main;
          ./main;
    depends_on:
      - db
    restart: always

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ADD_DB_NAME
      POSTGRES_USER: ADD_DB_USER
      POSTGRES_PASSWORD: ADD_DB_PASS
    ports:
      - "5432:5432"
    volumes:
      - ~/postgres/data/db:/var/lib/postgresql/data
    restart: always