name: Deploy to Linode

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Linode
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LINODE_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to the root directory
            APP_DIR="/root/DigitalDiary"
            if [ -d "$APP_DIR/.git" ]; then
              echo "Repository exists. Pulling latest changes..."
              cd "$APP_DIR"
              git fetch --all
              git reset --hard origin/master  # Use master branch
              git pull https://${{ secrets.PAT }}@github.com/fredericodes/DigitalDiary.git master  # Use PAT for private repo
            else
              echo "Repository does not exist. Cloning repository..."
              git clone https://${{ secrets.PAT }}@github.com/fredericodes/DigitalDiary.git "/root"  # Use PAT for private repo
            fi

            # Update BaseUrl in Route.cs (inside the cloned repo)
            LINODE_IP=${{ secrets.LINODE_IP }}
            sed -i "s|public static readonly string BaseUrl = \"http://localhost:7000\";|public static readonly string BaseUrl = \"http://${LINODE_IP}:7000\";|g" $APP_DIR/ui/api/Route.cs

            # Stop and remove existing containers
            docker-compose down

            # Clean up unused Docker resources
            docker system prune -a --volumes -f

            # Build and start the services
            docker-compose up -d --build