name: Deploy to Linode

on:
  push:
    branches:
      - master  # Use master branch
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Deploy to Linode via SSH
      - name: Deploy to Linode
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LINODE_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to the app directory
            APP_DIR="/root/DigitalDiary"
            if [ -d "$APP_DIR/.git" ]; then
              echo "Repository exists. Pulling latest changes..."
              cd "$APP_DIR"
              git fetch --all
              git reset --hard origin/master
              git pull https://${{ secrets.PAT }}@github.com/fredericodes/DigitalDiary.git master  # Use PAT for private repo
            else
              echo "Repository does not exist. Cloning repository..."
              git clone https://${{ secrets.PAT }}@github.com/fredericodes/DigitalDiary.git "$APP_DIR"  # Use PAT for private repo
              cd "$APP_DIR"
            fi

            # Update BaseUrl in Route.cs using perl
            API_DOMAIN=${{ secrets.API_DOMAIN }}
            perl -pi -e "s|http://localhost:7000|https://${API_DOMAIN}|g" "$APP_DIR/ui/Api/Route.cs"

            # Debug: Print the updated Route.cs file
            echo "Updated Route.cs file:"
            cat "$APP_DIR/ui/Api/Route.cs"

            # Stop and remove existing containers
            cd "$APP_DIR"
            docker-compose down

            # rebuild image
            docker-compose build

            # Build and start the services
            docker-compose up -d --build

            # Clean up unused Docker resources
            docker system prune -a --volumes -f

            # Debug: Check container logs
            docker-compose logs ui
            docker-compose logs api