name: Deploy to Linode

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Linode
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LINODE_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to the root directory
            APP_DIR="/root/DigitalDiary"
            if [ -d "$APP_DIR/.git" ]; then
              echo "Repository exists. Pulling latest changes..."
              cd "$APP_DIR"
              git fetch --all
              git reset --hard origin/master  # Use master branch
              git pull https://${{ secrets.PAT }}@github.com/fredericodes/DigitalDiary.git master  # Use PAT for private repo
            else
              echo "Repository does not exist. Cloning repository..."
              git clone https://${{ secrets.PAT }}@github.com/fredericodes/DigitalDiary.git "/root"  # Use PAT for private repo
            fi

            # Set BASE_URL environment variable
             export BASE_URL="http://${{ secrets.LINODE_IP }}:7000"

            # Stop and remove existing containers
            cd "$APP_DIR"
            docker-compose down

            # Clean up unused Docker resources
            docker system prune -a --volumes -f

            # Build and start the services with BASE_URL
            docker-compose up -d --build
